//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkircevObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public int StockItemID { get; set; }
        public string Quantity { get; set; }
        public string PricePerUnit { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual StockItems StockItems { get; set; }
    }
}
