//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkircevObuv
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.StockItems = new HashSet<StockItems>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductName { get; set; }
        public int ManufacturerID { get; set; }
        public string ProductDescription { get; set; }
        public string ProductComposititon { get; set; }
        public decimal ProductCost { get; set; }

        public string ProductPhotoPath
        {
            get
            {
                if (ProductPhoto == null)
                    return null;

                return "/products/" + ProductPhoto;
            }
        }

        public virtual Category Category { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItems> StockItems { get; set; }

        public string AvailableSizes
        {
            get
            {
                return string.Join(", ",
                    StockItems.Select(x => x.Sizes.SizeValue + " (" + x.QuantityAvailable + " шт.)"));
            }
        }
    }
}
